all:
	(cd cellular_automata; make)
	(cd elip_v2; make)
	(cd fibo; make)
	(cd planets; make)
	(cd primes; make)
	(cd reflex; make)

clean:
	(cd cellular_automata; make clean)
	(cd elip_v2; make clean)
	(cd fibo; make clean)
	(cd planets; make clean)
	(cd primes; make clean)
	(cd reflex; make clean)

realclean:
	(cd cellular_automata; make realclean)
	(cd elip_v2; make realclean)
	(cd fibo; make realclean)
	(cd planets; make realclean)
	(cd primes; make realclean)
	(cd reflex; make realclean)
cleanall: realclean