all:
	(cd cellular_automata; $(MAKE))
	(cd elip_v2; $(MAKE))
	(cd fibo; $(MAKE))
	(cd planets; $(MAKE))
	(cd primes; $(MAKE))
	(cd reflex; $(MAKE))
	(cd reactive_art; $(MAKE))
	(cd reactive_asco; $(MAKE))

clean:
	(cd cellular_automata; $(MAKE) clean)
	(cd elip_v2; $(MAKE) clean)
	(cd fibo; $(MAKE) clean)
	(cd planets; $(MAKE) clean)
	(cd primes; $(MAKE) clean)
	(cd reflex; $(MAKE) clean)
	(cd reactive_art; $(MAKE) clean)
	(cd reactive_asco; $(MAKE) clean)

realclean:
	(cd cellular_automata; $(MAKE) realclean)
	(cd elip_v2; $(MAKE) realclean)
	(cd fibo; $(MAKE) realclean)
	(cd planets; $(MAKE) realclean)
	(cd primes; $(MAKE) realclean)
	(cd reflex; $(MAKE) realclean)
	(cd reactive_art; $(MAKE) realclean)
	(cd reactive_asco; $(MAKE) cleanall)
cleanall: realclean
