
all:
	cd rmlbuild; $(MAKE)

opt: all
byte: all


install:
	cd rmlbuild; $(MAKE) install

uninstall:
	cd rmlbuild; $(MAKE) uninstall

clean:
	cd rmlbuild; $(MAKE) clean

realclean:
	cd rmlbuild; $(MAKE) realclean

cleanall: realclean

