# Lucid-Synchrone Simulator
# Author : Gregoire Hamon, Marc Pouzet 
# Organization : SPI team, LIP6 laboratory, University Paris 6 

all: dvi

html:

dvi:

clean:

realclean: clean


.PHONY:all html dvi clean realclean

